### ISSUE TITLE
Videresending til fylke være periode, ikke innen

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMvideresending#3]
Innføre "videresendingen er åpen fra $frist_start til $frist_stop". Legges inn av fylkeskontakt og UKM N i mønstringsmodulen

**Comment by AsgeirSH** [comment]
Har begynt på denne i UKMmonstring (GUI), men regner med det krever endringer i database (med mindre vi kan bruke deadline2 som startdato for fylkene?) og videresending. Tanker @mariusmandal?

**Comment by mariusmandal** [comment]
Deadline2 er ok

Mvh,

Marius Mandal

92837360

mariusmandal@gmail.com

—Sent from Mailbox
