### ISSUE TITLE
Allergier dukker ikke opp i videresendingsskjema

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMvideresending#4]
Oppland opplevde et problem med dette 7/4 (altså fra lokalmønstring til fylkesmønstring).
Er usikker på om feltet ikke dukket opp i skjema, eller om lagret data ikke ble lagret, eller at rapporten ikke viste lagret data

**Comment by AsgeirSH** [comment]
Både "Når kommer dere?" og "Allergier"-data ser ut til å bli lagret, men vises ikke i skjemaet på fylkessiden.

**Comment by mariusmandal** [comment]
Dette var en annen fix, men vi har nå fixet feilen også :)
